#!/usr/bin/env python3

import json
import sys
from pathlib import Path

request = json.load(sys.stdin)

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "pypkg"))

from hermes_user_domain import list_domain_users


json.dump({"users": list_domain_users(request["domain"])}, fp=sys.stdout)